export const countryCodes = [
    { name: "India", code: "91", iso: "IN" },
    { name: "United Arab Emirates", code: "971", iso: "AE" },
    { name: "Saudi Arabia", code: "966", iso: "SA" },
    { name: "United States", code: "1", iso: "US" },
    { name: "United Kingdom", code: "44", iso: "GB" },
    { name: "Afghanistan", code: "93", iso: "AF" },
    { name: "Albania", code: "355", iso: "AL" },
    { name: "Algeria", code: "213", iso: "DZ" },
    { name: "Andorra", code: "376", iso: "AD" },
    { name: "Angola", code: "244", iso: "AO" },
    { name: "Argentina", code: "54", iso: "AR" },
    { name: "Armenia", code: "374", iso: "AM" },
    { name: "Australia", code: "61", iso: "AU" },
    { name: "Austria", code: "43", iso: "AT" },
    { name: "Azerbaijan", code: "994", iso: "AZ" },
    { name: "Bahrain", code: "973", iso: "BH" },
    { name: "Bangladesh", code: "880", iso: "BD" },
    { name: "Belgium", code: "32", iso: "BE" },
    { name: "Brazil", code: "55", iso: "BR" },
    { name: "Canada", code: "1", iso: "CA" },
    { name: "China", code: "86", iso: "CN" },
    { name: "Egypt", code: "20", iso: "EG" },
    { name: "France", code: "33", iso: "FR" },
    { name: "Germany", code: "49", iso: "DE" },
    { name: "Indonesia", code: "62", iso: "ID" },
    { name: "Iran", code: "98", iso: "IR" },
    { name: "Iraq", code: "964", iso: "IQ" },
    { name: "Ireland", code: "353", iso: "IE" },
    { name: "Italy", code: "39", iso: "IT" },
    { name: "Japan", code: "81", iso: "JP" },
    { name: "Jordan", code: "962", iso: "JO" },
    { name: "Kuwait", code: "965", iso: "KW" },
    { name: "Lebanon", code: "961", iso: "LB" },
    { name: "Malaysia", code: "60", iso: "MY" },
    { name: "Netherlands", code: "31", iso: "NL" },
    { name: "New Zealand", code: "64", iso: "NZ" },
    { name: "Norway", code: "47", iso: "NO" },
    { name: "Oman", code: "968", iso: "OM" },
    { name: "Pakistan", code: "92", iso: "PK" },
    { name: "Philippines", code: "63", iso: "PH" },
    { name: "Portugal", code: "351", iso: "PT" },
    { name: "Qatar", code: "974", iso: "QA" },
    { name: "Russia", code: "7", iso: "RU" },
    { name: "Singapore", code: "65", iso: "SG" },
    { name: "South Africa", code: "27", iso: "ZA" },
    { name: "South Korea", code: "82", iso: "KR" },
    { name: "Spain", code: "34", iso: "ES" },
    { name: "Sri Lanka", code: "94", iso: "LK" },
    { name: "Sweden", code: "46", iso: "SE" },
    { name: "Switzerland", code: "41", iso: "CH" },
    { name: "Thailand", code: "66", iso: "TH" },
    { name: "Turkey", code: "90", iso: "TR" },
    { name: "Ukraine", code: "380", iso: "UA" },
    { name: "Vietnam", code: "84", iso: "VN" }
].sort((a,b) => a.name.localeCompare(b.name));
